### ISSUE TITLE
Serious Bug

### ISSUE THREAD

**Issue by TakeOwer** [GerB/autoresponder#3]
Hi,
I installed this extension, but it creates quite a few problems!
The fields `ar_user_id` and `ar_message_template` created by this extension cause some errors. If I access any forum from ACP, it displays a gray page. When this extension was installed, and I went to create forums, it didn't let me create them Displaying this message `ar_message_template` doesn't have a default value phpbb.
I would like some help to solve this problem :)

Thank you and have a nice day
Salvo

**Comment by GerB** [comment]
https://www.phpbb.com/community/viewtopic.php?p=16000087#p16000087
Sorry. Like I wrote there, if anyone wants to take over this extension can be forked.
